### PR TITLE
Update FCFS.java 1jc May16

### PR DESCRIPTION
**Pull request by 1jc**
Update FCFS.java 1jc May16 reference pull #15

### CODE REVIEW

**Review by natrimmer — CHANGES_REQUESTED** [review]
Lines 52 and 57 have errors. I'm guessing they should both be waitingTime[i] = ... & turnaroundTime[i] = ...

Fix that and I'll review again.

**Comment by 1jc** [comment]
1jc made additional changes to PR #22

**Review by natrimmer — CHANGES_REQUESTED** [review]
On top of that minor change, the code compiles now, but those arrays don't actually do anything considering waiting time for each process and turnaround time for each process are calculated by your algorithm. as it stands right now, all this does is gather waiting times and turnaround times for each process before either of those data are set. those data are set by process execution in your algorithm. getting waiting time or turnaround time before setting them does not do anything.

**Comment by 1jc** [comment]
Joette Damo
  [9:49 PM](https://nsccs.slack.com/archives/C0501TD3LMV/p1684298972704819)
[@Nick Trimmer](https://nsccs.slack.com/team/U044PEV585N)
 what it needs as I have researched for FCFS is the average time for the waiting time and the average time for the turnaround time but I do not see the process in the utility processes for average waiting time function or a function for average turn around time in the processes  (in research does not ask for start    times)      here is what FCFS        needs in         implementation                                                Implementation:
1-  Input the processes along with their burst time (bt).
2-  Find waiting time (wt) for all processes.
3-  As first process that comes need not to wait so 
    waiting time for process 1 will be 0 i.e. wt[0] = 0.
4-  Find waiting time for all other processes i.e. for
     process i -> 
       wt[i] = bt[i-1] + wt[i-1] .
5-  Find turnaround time = waiting_time + burst_time 
    for all processes.
6-  Find average waiting time = 
                 total_waiting_time / no_of_processes.
7-  Similarly, find average turnaround time = 
                 total_turn_around_time / no_of_processes.

**Comment by 1jc** [comment]
1jc additional 2nd changes May 16 11:11 pm

**Pull request merged**
